version: '3.9'

services:
  server:
    build: .
    image: gcr.io/glowing-reserve-336013/fixme
    ports:
      - "1337:1337"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
      start_period: 2s