version: '3.8'

services:
  app:
    build: .
    ports:
      - '1337:80'
    image: gcr.io/glowing-reserve-336013/sqli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
