version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3008:5000'
    image: gcr.io/glowing-reserve-336013/reflected-note
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
