#!/bin/bash
 
if [ ! -r secret ]; then
    echo "secret file is missing"
    exit 1
fi

secret=$(cat secret)

if [ -z "${1}" ]; then
    echo "USAGE : $0 your_guess"
    exit 1
fi
    
if [ $secret = "${1}" ] ; then
    echo "WOOAH! You are such a supper guesser, you will be a good ctf player"
else
    echo "WROOONG GUESS !!"
fi
 
exit 0
    