version: '3.3'

services:

  app:
    build: .
    ports:
      - '2223:22'
    image: gcr.io/glowing-reserve-336013/path
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

