version: '3.8'

services:

  server:
    build: .
    ports:
      - '2221:22'
    image: gcr.io/glowing-reserve-336013/cowsay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

