version: "3.8"

services:

  web:
    build: .
    ports:
      - '1337:1337'
    image: gcr.io/glowing-reserve-336013/my-first-sqli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
