

light = ['off', 'on', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'on', 'off', 'off', 'off', 'off', 'on', 'off', 'on', 'on', 'on', 'off', 'on', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'off', 'off', 'off', 'on', 'on', 'on', 'off', 'off', 'off', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'off', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'off', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'on', 'off', 'off', 'on', 'off', 'off', 'off', 'on', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'on', 'on', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'off', 'off', 'off', 'on', 'on', 'on', 'off', 'on', 'off', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'off', 'on', 'off', 'on', 'on', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'off', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'off', 'on', 'off', 'on', 'off', 'on', 'off', 'on', 'off', 'off', 'on', 'on', 'off', 'on', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'on', 'on', 'off', 'off', 'off', 'on', 'off', 'on', 'off', 'off', 'off', 'on', 'on', 'on', 'off', 'on', 'on', 'off', 'on', 'off', 'off', 'off', 'off', 'on', 'on', 'on', 'on', 'on', 'off', 'on']

f = lambda s: '1' if s == 'on' else '0'

bi = ''.join(list(map(f, light)))

flag = ''.join( [ chr(int(bi[i:i+8], 2)) for i in range(0, len(bi), 8) ] )

print(flag)
