version: '3.3'

services:

  linux2:
    build: .
    ports:
      - '2222:22'
    image: gcr.io/glowing-reserve-336013/linux2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

